// Generated from Template_Data.xlsx

export const WEATHER_OPTIONS = [
    "Clear",
    "Clear Air Turbulence",
    "Crosswinds",
    "Dust",
    "Fog",
    "High Seas",
    "Hurricane/Typhoon",
    "Ice",
    "Icing",
    "Lightning",
    "Low Ceiling",
    "Low Visibility",
    "Rain",
    "Rain - Drizzle",
    "Rain - Freezing",
    "Rain - Heavy",
    "Rain - Light",
    "Sandstorm",
    "Snow",
    "Thunderstorm",
    "Tornado",
    "Turbulence",
    "Wind",
    "Winds - Gusting"
];

export const CANCELLATION_CRITERIA = [
    { label: "Aircraft", responsible: "Shield AI" },
    { label: "Avionics", responsible: "Shield AI" },
    { label: "Back Up AV Used", responsible: "Shield AI" },
    { label: "Camera Replaced", responsible: "Shield AI" },
    { label: "Comm's Loss", responsible: "Shield AI" },
    { label: "Comm's Poor", responsible: "Shield AI" },
    { label: "Customer Directed", responsible: "Shield AI" },
    { label: "DGPS Failure", responsible: "Shield AI" },
    { label: "Engine", responsible: "Shield AI" },
    { label: "Engine - High RPM", responsible: "Shield AI" },
    { label: "Engine - High Temp", responsible: "Shield AI" },
    { label: "Engine - Low RPM", responsible: "Shield AI" },
    { label: "Engine - Tach", responsible: "Shield AI" },
    { label: "Engine Replaced", responsible: "Shield AI" },
    { label: "Flight Controls", responsible: "Shield AI" },
    { label: "Fuel - Contaminated", responsible: "Shield AI" },
    { label: "GCS Malfunction", responsible: "Shield AI" },
    { label: "Generator - AC", responsible: "Shield AI" },
    { label: "Generator - Customer", responsible: "Shield AI" },
    { label: "Generator - Ground", responsible: "Shield AI" },
    { label: "GPS - AC", responsible: "Shield AI" },
    { label: "GPS - Ground", responsible: "Shield AI" },
    { label: "Ground Equipment", responsible: "Shield AI" },
    { label: "Interference/Jamming", responsible: "Other" },
    { label: "Late Flight Authorization", responsible: "Other" },
    { label: "No Reason Given", responsible: "TBD" },
    { label: "Other", responsible: "Other" },
    { label: "Ship - Other", responsible: "USCG" },
    { label: "Turret", responsible: "Shield AI" },
    { label: "Turret Malfunction", responsible: "Shield AI" },
    { label: "Video", responsible: "Shield AI" },
    { label: "Video None", responsible: "Shield AI" },
    { label: "Video Poor", responsible: "Shield AI" },
    { label: "Weather", responsible: "Other" },
    { label: "Weather - Clear Air Turbulence", responsible: "Other" },
    { label: "Weather - Crosswinds", responsible: "Other" },
    { label: "Weather - Dust", responsible: "Other" },
    { label: "Weather - Fog", responsible: "Other" },
    { label: "Weather - High Seas", responsible: "Other" },
    { label: "Weather - Hurricane/Typhoon", responsible: "Other" },
    { label: "Weather - Icing", responsible: "Other" },
    { label: "Weather - Lightning", responsible: "Other" },
    { label: "Weather - Low Ceiling", responsible: "Other" },
    { label: "Weather - Low Visibility", responsible: "Other" },
    { label: "Weather - Rain", responsible: "Other" },
    { label: "Weather - Rain - Drizzle", responsible: "Other" },
    { label: "Weather - Rain - Freezing", responsible: "Other" },
    { label: "Weather - Rain - Heavy", responsible: "Other" },
    { label: "Weather - Rain - Light", responsible: "Other" },
    { label: "Weather - Sandstorm", responsible: "Other" },
    { label: "Weather - Snow", responsible: "Other" },
    { label: "Weather - Thunderstorm", responsible: "Other" },
    { label: "Weather - Tornado", responsible: "Other" },
    { label: "Weather - Turbulence", responsible: "Other" },
    { label: "Weather - Wind", responsible: "Other" },
    { label: "Weather - Winds - Gusting", responsible: "Other" },
    { label: "Wing Replacement", responsible: "Shield AI" },
    { label: "DGPS", responsible: "Shield AI" },
    { label: "Engine - Cut", responsible: "Shield AI" },
    { label: "Fuel - Low", responsible: "Shield AI" },
    { label: "Fuel -  Ran out of Fuel", responsible: "Shield AI" },
    { label: "Poor Communication", responsible: "Shield AI" },
    { label: "Equipment Failure", responsible: "Shield AI" },
    { label: "Fuel - Fuel Sensor Calibration", responsible: "Shield AI" },
    { label: "Fuel - None on hand", responsible: "Shield AI" },
    { label: "High RPM", responsible: "Shield AI" },
    { label: "Low RPM", responsible: "Shield AI" },
    { label: "Out of AO", responsible: "Client" },
    { label: "Ship - RAS", responsible: "Client" }
];

export const getResponsibleParty = (reason) => {
    const item = CANCELLATION_CRITERIA.find(c => c.label === reason);
    return item ? item.responsible : 'TBD';
};
