require('dotenv').config();
const express = require('express');
const cors = require('cors');
const sequelize = require('./config/database');
const Flight = require('./models/Flight');
const Equipment = require('./models/Equipment');
const Deployment = require('./models/Deployment');
const ApiKey = require('./models/ApiKey');

const app = express();
const PORT = process.env.PORT || 3001;

// Middleware
app.use(cors());
app.use(express.json());

// Auth Middleware
const authenticateApiKey = async (req, res, next) => {
    const key = req.header('X-API-Key');
    if (!key) return res.status(401).json({ error: 'API Key missing' });

    try {
        const apiKey = await ApiKey.findOne({ where: { key, status: 'Active' } });
        if (!apiKey) {
            return res.status(403).json({ error: 'Invalid or revoked API Key' });
        }
        next();
    } catch (error) {
        console.error('Auth Error:', error);
        res.status(500).json({ error: 'Internal Server Error' });
    }
};

// Routes

// GET /flights
app.get('/v1/flights', authenticateApiKey, async (req, res) => {
    try {
        const { startDate, endDate, deploymentId } = req.query;
        const where = {};

        if (startDate && endDate) {
            where.date = {
                [require('sequelize').Op.between]: [new Date(startDate), new Date(endDate)]
            };
        }
        if (deploymentId) {
            where.deploymentId = deploymentId;
        }

        const flights = await Flight.findAll({ where });
        res.json(flights);
    } catch (error) {
        console.error('Error fetching flights:', error);
        res.status(500).json({ error: 'Failed to fetch flights' });
    }
});

// POST /flights
app.post('/v1/flights', authenticateApiKey, async (req, res) => {
    try {
        const flight = await Flight.create(req.body);
        res.status(201).json(flight);
    } catch (error) {
        console.error('Error creating flight:', error);
        res.status(500).json({ error: 'Failed to create flight' });
    }
});

// GET /equipment
app.get('/v1/equipment', authenticateApiKey, async (req, res) => {
    try {
        const equipment = await Equipment.findAll();
        res.json(equipment);
    } catch (error) {
        console.error('Error fetching equipment:', error);
        res.status(500).json({ error: 'Failed to fetch equipment' });
    }
});

// Admin Route to Create Keys (for initial setup/testing via Postman/Curl)
// In a real scenario, this would be protected or generated by the UI -> DB directly if they share DB.
app.post('/v1/admin/keys', async (req, res) => {
    try {
        const { name, key } = req.body;
        // Simple check to prevent public abuse in this demo
        // if (req.header('X-Admin-Secret') !== 'super-secret') return res.sendStatus(403);

        const newKey = await ApiKey.create({ name, key });
        res.status(201).json(newKey);
    } catch (error) {
        res.status(500).json({ error: error.message });
    }
});

// Initialize DB and Start Server
sequelize.sync().then(() => {
    console.log('Database synced');
    app.listen(PORT, () => {
        console.log(`Server running on port ${PORT}`);
    });
}).catch(err => {
    console.error('Failed to sync database:', err);
});
